### ISSUE TITLE
It's not possible to open apk files

### ISSUE THREAD

**Issue by lucas404x** [bertoldofonseca/better_open_file#1]
This fork is a great job, but unfortunately it's not possible to open apk files since you removed the "REQUEST_INSTALL" permission. Is there any plan to put it again?

**Comment by Harishwarrior** [comment]
> This fork is a great job, but unfortunately it's not possible to open apk files since you removed the "REQUEST_INSTALL" permission. Is there any plan to put it again?

Use the open_file package if you want to open APK.

**Comment by lucas404x** [comment]
I'm using it but it's ready for Flutter v3, so there are a bunch of libraries outdated.

**Comment by Harishwarrior** [comment]
> I'm using it but it's ready for Flutter v3, so there are a bunch of libraries outdated.

Read readme, this package will never add apk functionality.

**Comment by WatchDogsDev** [comment]
> This fork is a great job, but unfortunately it's not possible to open apk files since you removed the "REQUEST_INSTALL" permission. Is there any plan to put it again?

@Harishwarrior is correct. 

The plugin shouldn't add the install package permission by default but if you want it, You can simply add permission in your `AndroidManifest.xml` :

```
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
```

**Comment by lucas404x** [comment]
> > This fork is a great job, but unfortunately it's not possible to open apk files since you removed the "REQUEST_INSTALL" permission. Is there any plan to put it again?
> 
> @Harishwarrior is correct.
> 
> The plugin shouldn't add the install package permission by default but if you want it, You can simply add the permission in your `AndroidManifest.xml` :
> 
> ```
> <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
> ```

Thanks! It works like a charm 😁
