### ISSUE TITLE
Remove `READ_EXTERNAL_STORAGE` permission

### ISSUE THREAD

**Issue by WatchDogsDev** [bertoldofonseca/better_open_file#3]
Hi,

Is it possible to remove the `READ_EXTERNAL_STORAGE` permission from AndroidManifest.xml ? (like [open_app_file](https://pub.dev/packages/open_app_file) package)
So we let anyone using it, Add it to his manifest. (We can add the document to readme file)

**Comment by bertoldofonseca** [comment]
Hi @WatchDogsDev, I will check and get back to you.
